Add Ecs:ListTagsForResources support
erlcloud/erlcloud pull request #679
Opened 2020-12-15 15:47 UTC by kkuzmin

https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_ListTagsForResource.html

I haven't found any specific reason for having `#ecs_tags{}` record with the only `tags` list field in it. The new `list_tags_for_resource()` method simply returns the list of `#ecs_tag{}` records 
```
{ok, [
    #ecs_tag{},
    #ecs_tag{},
    ...
  ]
}
```

instead of 
```
{ok, #ecs_tags{
  tags = [
    #ecs_tag{},
    #ecs_tag{},
    ...
  ]
}}
```

2020-12-15 19:22 UTC, nalundgaard requested changes
LGTM, I think I agree on not having a wrapping record, can probably let clients get raw decoded JSON on the case that anything else is needed. Just the issue with the output specs, I guess should be `ecs_return([#ecs_tag{}]).`

2020-12-16 11:16 UTC, kkuzmin commented
@nalundgaard addressed. Thank you.

2020-12-17 16:41 UTC, nalundgaard commented on src/erlcloud_ecs.erl
> +%%%------------------------------------------------------------------------------
It looks like the style is to have a section heading like this at the "top"

```erlang
%%%------------------------------------------------------------------------------
 %% ListTagsForResource
 %%%------------------------------------------------------------------------------
```

Then put this block with the full docs above the highest arity function, `list_tags_for_resource/3` here. I think that's the last change and G2G.

2020-12-17 16:43 UTC, nalundgaard commented on test/erlcloud_ecs_tests.erl
> +      fun list_tags_for_resource_input_tests/1,
can you put these between `list_services_output_tests/1` and `list_task_definition_families_input_tests/1` as well?

2020-12-17 16:47 UTC, nalundgaard approved these changes

2020-12-17 16:48 UTC, nalundgaard commented on test/erlcloud_ecs_tests.erl
> +      fun list_tags_for_resource_output_tests/1
looks like missing comma here causing CI to fail, actually.

2020-12-17 17:42 UTC, merged