Add missing set types for (un)dynamize_type
erlcloud/erlcloud pull request #696
Opened 2021-04-12 06:46 UTC by lehoff

SS, NS and BS are supported elsewhere, but not in these two functions
and that makes it impossible to create tables using any of the set
types.
Only SS has been tested, but given the similarity of these types one
might consider that enough.

2021-04-12 07:55 UTC, lehoff commented
Found a problem using this. Will return with an expanded test case and a fix.

2021-04-12 08:11 UTC, lehoff commented
I had a usage problem - the code should be okay.

2021-04-12 14:05 UTC, nalundgaard requested changes
I think this PR probably rests on a misunderstanding/misuse of the DynamoDB API. You actually cannot use SS/NS/BS in [AttributeDefinitions](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeDefinition.html); only S, N, and B are supported. [`dynamize_type/1`](https://github.com/erlcloud/erlcloud/blob/23960fc/src/erlcloud_ddb2.erl#L426-L432) is [only used in `dynamize_attr_defs /1`](https://github.com/erlcloud/erlcloud/blob/23960fc/src/erlcloud_ddb2.erl#L498-L505), and [`undynamize_type/1`](https://github.com/erlcloud/erlcloud/blob/23960fc/src/erlcloud_ddb2.erl#L724-L730) is [only used in `undynamize_attr_defs/1`](https://github.com/erlcloud/erlcloud/blob/23960fc/src/erlcloud_ddb2.erl#L829-L833). So, while this PR will facilitate you forming a bogus request that will be rejected by AWS, it doesn't actually improve anything. SS, BS, and NS are already supported in the places you can legitimately use them [here](https://github.com/erlcloud/erlcloud/blob/23960fc/src/erlcloud_ddb2.erl#L462-L467) and [here](https://github.com/erlcloud/erlcloud/blob/23960fc/src/erlcloud_ddb2.erl#L753-L758).

Does this help @lehoff? Please correct me if I'm wrong, I'd appreciate a more concrete example of the problem you're facing to understand how this might correct it.

2021-04-13 07:40 UTC, lehoff commented
@nalundgaard You are right, this is incorrect usage. Deleting it.

2021-04-13 07:40 UTC, closed without merging

2021-04-13 07:41 UTC, lehoff commented on test/erlcloud_ddb2_tests.erl
> +                    {<<"Posters">>, ss}],
I was on a red herring chase due to a misunderstanding. PR retracted.