Ensure metadata api token header on metadata fetch
erlcloud/erlcloud pull request #750
Opened 2023-04-28 14:49 UTC by xmppjingle

2023-05-03 09:16 UTC, motobob requested changes
need to handle non EC2 cases.

2023-05-08 17:48 UTC, carlisom commented on src/erlcloud_ec2_meta.erl
> +    erlcloud_aws:http_body(erlcloud_httpc:request(MetaDataPath, get, Headers, <<>>, erlcloud_aws:get_timeout(Config), Config)).
This looks correct, `put` is used to generate the token which is done in `get_metadata_api_token` while the `get` is used to retrieve the meta data. Documentation is [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-metadata-v2-how-it-works.html)

2023-05-08 18:09 UTC, carlisom requested changes
Yes, the error from `get_metadata_api_token` needs to be sent to the caller to be handled accordingly vs the current `bad match` that will be encountered.

2023-05-08 18:10 UTC, carlisom requested changes
Yes, the error from `get_metadata_api_token` needs to be sent to the caller to be handled accordingly vs the current `bad match` that will be encountered.

2023-05-30 09:49 UTC, closed without merging