Add secretsmanager.PutSecretValue
erlcloud/erlcloud pull request #761
Opened 2023-10-30 13:49 UTC by sergioffpc

Implement missing secretsmanager.PutSecretValue.

2023-10-30 13:55 UTC, motobob commented on src/erlcloud_sm.erl
> +            (Other) -> Other
is it a good idea to leak open interface here? maybe at least limits to `{binary(), term()}`

2023-11-08 16:26 UTC, carlisom commented
Please add some test to [erlcloud_sm_tests](https://github.com/erlcloud/erlcloud/blob/master/test/erlcloud_sm_tests.erl) and we can get this merged.

2023-11-08 16:26 UTC, carlisom requested changes
Please add some test to [erlcloud_sm_tests](https://github.com/erlcloud/erlcloud/blob/master/test/erlcloud_sm_tests.erl) and we can get this merged.

2023-11-13 16:23 UTC, carlisom approved these changes

2023-11-13 17:16 UTC, merged